site_url: https://oosquare.github.io/

backend:
  name: github
  repo: oosquare/oosquare.github.io
  branch: master
  commit_messages:
    create: 'feat(content): create {{collection}} "{{slug}}"'
    update: 'feat(content): update {{collection}} "{{slug}}"'
    delete: 'feat(content): delete {{collection}} "{{slug}}"'
    updateMedia: 'feat(media): update media "{{path}}"'
    deleteMedia: 'feat(media): delete media "{{path}}"'
    openAuthoring: "{{message}}"

publish_mode: editorial_workflow

media_folder: "assets/images"
public_folder: "/images"

collections:
  - name: "post"
    label: "Post"
    folder: "content/posts"
    slug: "{{slug}}"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "draft", label: "Draft", widget: "boolean", default: true }
      - { name: "categories", label: "Categories", widget: "string", default: "Uncategorized" }
      - { name: "tags", label: "Tags", widget: "list", default: [] }
      - { name: "body", label: "Body", widget: "markdown" }
